### ISSUE TITLE
does setup_compile_commands.sh copy proper files

### ISSUE THREAD

**Issue by mellery451** [vincent-picaud/Bazel_and_CompileCommands#7]
I'm not sure I understand how this is supposed to work, but all the files that are installed by the setup script are just one-line files containing something like `<<...path/to/the/file ..>>`. As a result, the result of running this script for me is:

```
Create tools/actions/BUILD
Create tools/actions/generate_compile_command.py
Create tools/actions/generate_compile_commands_json.py
Create third_party/bazel/protos/extra_actions_base.proto
Generate third_party/bazel/protos/extra_actions_base_pb2.py
[libprotobuf WARNING google/protobuf/compiler/parser.cc:646] No syntax specified for the proto file: third_party/bazel/protos/extra_actions_base.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
third_party/bazel/protos/extra_actions_base.proto:1:1: Expected top-level statement (e.g. "message").
```
..which is the `protoc` compiler complaining about a proto file that is very much not a proto file (it's just the bracket file path as indicated above). 

Am I doing something fundamentally wrong with this script?

**Comment by wackston** [comment]
The last commit on master repalce the actual content of the generated files in the setup_ script with placeholders.  Presumably in preparation for adding support for downloading updateable versions of the content but commited prematurely.  Go back to commit db2f5581d618547205575f5efcb7ea2bd68ac11d and all should be well.

**Comment by vincent-picaud** [comment]
Dear mellery451,

Sorry for the delay, I just read your issue now (17 days later!).
Did you solve your problem?
-- Vincent

**Comment by i8run** [comment]
Hi @mellery451 , I met the same error, which can be solved by upgrading the protobuf to v3.7.0+. Thanks.

**Comment by vincent-picaud** [comment]
Hi @i8run ,
Thank you so much for this important feedback!
I hope it will solve @mellery451 problem too.

**Comment by mellery451** [comment]
I'm already on protoc 3.11, so I don't think that's the issue. I think @wackston is correct - something is not right with current HEAD. Resetting to db2f558 does seem to resolve the problems for me. Should we be relying on a particular tag or release for this project?

**Comment by vincent-picaud** [comment]
Hi @mellery45,

Thank you for your feedback.
 
I reopened the issue because It would be fine to understand what's going wrong with HEAD. The only change is that the shell script can forward several arguments instead of just one. By example, it allows to write 
```
create_compile_commands.sh \
   --action_env CC=/usr/bin/gcc-5 \
   --action_env CPP=/usr/bin/cpp-5 \
   --action_env CXX=/usr/bin/c++-5 \
   --verbose_failures //source/exe:envoy-static
```
which was not possible before.

Maybe you can check that you only have _one_ argument following the `create_compile_commands.sh`  command (maybe space in path or filename?).

To be honest I do not use "Bazel_and_CompileCommands" anymore for the moment (because I switched from Bazel to Meson build system). I will let this issue open in the event others encounter the same problem.

I also noticed that it does not work with python 3, one must use
`
create_compile_commands.sh --host_force_python=PY2 ...
 `
to force python2 over python3 (depending on your system configuration).

Best,
--Vincent

**Comment by nabroyan** [comment]
@wackston 's comment really solves the problem.

**Comment by vincent-picaud** [comment]
Thank you all for the feedbacks,
I have reseted master branch to db2f558 as this seems to solve the problem.
The old master branch that seems buggy is now the "weird_bug_to_fix" branch.
As I do not use Bazel for the moment I do not know when I will have time to have a look.
Hope current master branch is ok now.
Best,
-- Vincent
